### ISSUE TITLE
Having trouble implementing load-conn

### ISSUE THREAD

**Issue by MohdAhmad** [bronze1man/goStrongswanVici#1]
Hi @bronze1man,

I am trying to implement some additional functions that I need. I have successfully implemented a load-shared() but am having trouble implementing a load-conn(). I am hoping you can guide me in the right direction. 

For load-conn() there isn't any clear definition of the fields required on the vici github page https://github.com/strongswan/strongswan/tree/master/src/libcharon/plugins/vici and I followed the field names listed in the list-conn() section.

Here are the structs I have defined. 

type IKEConf struct {
        Local_addrs  []string               `json:"local_addrs"`
        Remote_addrs []string               `json:"remote_addrs"`
        Version      string                 `json:"version"`
        Children     map[string]ChildSAConf `json:"children"` //string is the childSAConfig name
        Local        map[string]AuthConf    `json:"local"`
        Remote       map[string]AuthConf    `json:"remote"`
}

type ChildSAConf struct {
        Mode      string   `json:"mode"`
        Local_ts  []string `json:"local-ts"`
        Remote_ts []string `json:"remote-ts"`
}

type AuthConf struct {
        AuthMethod string `json:"class"` //psk
}

And here is the load-conn function. 

func (c *ClientConn) LoadConn(conf *IKEConf) error {
    requestMap := &map[string]interface{}{}

```
err := ConvertToGeneral(conf, requestMap)
fmt.Printf("requestMap: %+v \n ", requestMap)

if err != nil {
    return fmt.Errorf("error creating request: %v", err)

}
msg, err := c.Request("load-conn", *requestMap)
if msg["success"] != "yes" {
    return fmt.Errorf("unsuccessful LoadConn: %v", msg["success"])
}

fmt.Printf("Msg[success]: %v", msg["success"])
return nil
```

}

Here is the main
        client, err := goStrongswanVici.NewClientConnFromDefaultSocket()
        if err != nil {
                panic(err)
        }
        defer client.Close()

```
    //get strongswan version
    v, err := client.Version()
    if err != nil {
            panic(err)
    }
    fmt.Printf("%#v\n", v)

    fmt.Printf("------------------------------------------------------------------- \n\n")

    childConfMap := make(map[string]goStrongswanVici.ChildSAConf)
    childSAConf := goStrongswanVici.ChildSAConf{
            Local_ts:  []string{"10.10.20.0/24"},
            Remote_ts: []string{"10.10.30.0/24"},
            Mode:      "tunnel",
    }
    childConfMap["child-sa-config-tmp"] = childSAConf

    localAuthMap := make(map[string]goStrongswanVici.AuthConf)
    localAuthConf := goStrongswanVici.AuthConf{
            AuthMethod: "psk",
    }   
    localAuthMap[""] = localAuthConf

    remoteAuthMap := make(map[string]goStrongswanVici.AuthConf)
    remoteAuthConf := goStrongswanVici.AuthConf{
```

   AuthMethod: "psk",
        }  
        localAuthMap[""] = localAuthConf

```
    remoteAuthMap := make(map[string]goStrongswanVici.AuthConf)
    remoteAuthConf := goStrongswanVici.AuthConf{
            AuthMethod: "psk",
    }
    remoteAuthMap[""] = remoteAuthConf
    ikeConf := &goStrongswanVici.IKEConf{
            Local_addrs:  []string{"192.168.198.1"},
            Remote_addrs: []string{"192.168.198.20"},
            Version:      "1",
            Local:        localAuthMap,
            Remote:       remoteAuthMap,
            Children:     childConfMap,
    }

    err = client.LoadConn(ikeConf)
    if err != nil {
            fmt.Printf("error loading connection: %v")
            panic(err)
    }
```

Error message I get is:
request goStrongswanVici.segment{typ:0x1, name:"", msg:map[string]interface {}{"success":"no", "errmsg":"invalid section: child-sa-config-tmp"}}

Any suggestions on what may be going wrong? I appreciate your help and can submit a PR for review if that helps.

**Comment by MohdAhmad** [comment]
@bronze1man I have updated the above message and made changes to the code. Still getting an error though.

**Comment by MohdAhmad** [comment]
After removing the Children, Local and Remote maps from the IKEConf struct the request goes through. I expect that there is some issue with how I deal with the maps then.

**Comment by MohdAhmad** [comment]
Got this working. Yay!
If you are willing to accept PRs, I will submit one soon.

**Comment by bronze1man** [comment]
I am willing to accept PRs.
I am waiting for your PRs.

**Comment by MohdAhmad** [comment]
@bronze1man Sounds good. I have a little trouble trying to installpolicy=no through the vici plugin. Once I have that figured out, I will be able to send in the PR.
