### ISSUE TITLE
Fetching a list of conns, sas is returning a map instead of a slice

### ISSUE THREAD

**Issue by leodotcloud** [bronze1man/goStrongswanVici#10]
While fetching a list of connections and SAs from the kernel, some of the functions are returning maps which are keyed/indexed by name. But in the kernel it is possible to have multiple connections with the same name.

- https://github.com/bronze1man/goStrongswanVici/blob/master/listConns.go#L7
- https://github.com/bronze1man/goStrongswanVici/blob/master/listSas.go#L83

Since this library is already being used many others, it's not a good idea to break the API. May be in a later version, this functionality can be changed.
To overcome this limitation, we have modified the readMap function to be able to handle duplicate keys: https://github.com/rancher/goStrongswanVici/commit/c0828c2fbfeb9088aa61e3ea3144e507fa6a2adb. This has worked out well for us and this code has been tested multiple times and also being used in production environments too.

For the benefit of others, I can submit the above patch as a PR.

What do you think @bronze1man?

**Comment by bronze1man** [comment]
I think you idea is good.
but the code looks wired to me.
Why not add a function called mapAddKey instead of getKey?
I found that you want to add a key to map. So the meaning of getKey is wired.

**Comment by leodotcloud** [comment]
@bronze1man I have renamed the function to something more meaningful and also added comments to make it easier to understand. Can you please review?
