### ISSUE TITLE
Modify ipsec.secrets

### ISSUE THREAD

**Issue by EminBudak** [bronze1man/goStrongswanVici#23]
Is there any function to add a new username and password or remove user via goStrongswanVici? (ipsec.secrets)

**Comment by bronze1man** [comment]
I think you are looking https://github.com/bronze1man/goStrongswanVici/blob/master/shared.go#L25

* search `load-shared()` in https://github.com/strongswan/strongswan/tree/master/src/libcharon/plugins/vici

sorry, I do not use this feature, please do the experiment before go to production.

**Comment by EminBudak** [comment]
I tried shared functions but they are not working. 

**My /etc/ipsec.secrets content**
```
include /var/lib/strongswan/ipsec.secrets.inc

# This is private key located at /etc/ipsec.d/private/piratekey.pem
: RSA privatekey.pem
test : EAP "passwordtest"
test2 : EAP "passwordtest2"
```




- UnloadShared it doesn't give an error but it is not working. I cannot remove line /etc/ipsec.secrets
- GetShared  it doesn't give an error but it is not working. I cannot retrieve /etc/ipsec.secrets lines it returns null array
- LoadShared gives an error. 

```
	client, err := goStrongswanVici.NewClientConnFromDefaultSocket()
	if err != nil {
		panic(err)
	}
	defer client.Close()

	err = client.LoadShared(&goStrongswanVici.Key{
		ID: "testuser",
		Typ: "EAP",
		Data: "testpassword",
	})
	if err != nil {
		panic(err) 
	}
```

> error retruned from writeMap 
> error writing segment

**Comment by EminBudak** [comment]
I tried GetShared & UnloadShared again and these are works well. because I found that these are using /etc/swanctl/swanctl.conf file rather than /etc/ipsec.secrets. I add a user manually to /etc/swanctl/swanctl.conf file and list & remove functions worked. But LoadShared still gives an error.

**Comment by EminBudak** [comment]
I have done LoadShared function integration I tried various calls and I understood that OWNERS variable is needed. I passed it as "%any"
