### ISSUE TITLE
IP Xfrm Policy

### ISSUE THREAD

**Issue by shubham-gaur** [bronze1man/goStrongswanVici#30]
I am able to initiate tunnels in psk mode as well as in cert mode. I am able to see xfrm state changing but no policy getting added in xfrm policy. Can you please help me with the same

**Comment by bronze1man** [comment]
sorry, I do not know what xfrm is. May be we can start add some relative field from the document.
```
if-id-in = <hex encoded default inbound XFRM interface ID>
if-id-out = <hex encoded default outbound XFRM interface ID>
```
https://godoc.org/github.com/bronze1man/goStrongswanVici#IkeSa
https://github.com/strongswan/strongswan/tree/master/src/libcharon/plugins/vici

**Comment by shubham-gaur** [comment]
Hi, Thanks! for the help. I got it resolved by changing the `installPolicy: "yes"` in `client.loadConn`.
